In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
x= df.iloc[:,2:4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [9]:
y= df.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 1/5, random_state = 3)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
se = StandardScaler()

In [15]:
x_train=se.fit_transform(x_train)

In [16]:
x_test=se.fit_transform(x_test)

In [17]:
x_train

array([[ 1.4167466 ,  2.15546758],
       [-0.26616955,  0.05500764],
       [ 0.38829784,  2.33297124],
       [ 0.66878386, -1.4241895 ],
       [ 0.85577455, -0.56625516],
       [ 0.38829784,  0.29167919],
       [ 0.10781182,  1.0608617 ],
       [ 0.01431647, -0.32958361],
       [ 0.2948025 , -0.21124784],
       [-0.17267421, -0.5958391 ],
       [-0.54665557,  1.38628507],
       [-1.29461831, -1.12835007],
       [-1.10762762,  0.05500764],
       [ 0.85577455,  2.18505153],
       [ 0.94926989, -1.09876613],
       [ 0.94926989,  1.80046027],
       [-0.73364626,  0.29167919],
       [ 1.97771865,  0.17334342],
       [ 0.76227921, -0.86209458],
       [-1.01413228, -0.35916756],
       [-0.35966489,  1.23836536],
       [-1.85559036,  0.35084707],
       [-1.01413228, -0.47750333],
       [-1.20112297,  0.26209524],
       [ 1.8842233 , -1.39460555],
       [-0.54665557,  1.91879604],
       [-1.10762762, -1.57210921],
       [ 0.38829784,  1.12002959],
       [-0.64015092,

In [18]:
x_test

array([[ 0.96187955,  0.16714439],
       [ 1.0674356 , -1.23286847],
       [ 2.33410826, -1.1185817 ],
       [-1.78257787, -0.54714788],
       [-1.04368549,  0.59571976],
       [ 0.32854322,  0.28143116],
       [ 1.48965982, -1.29001185],
       [-1.46590971, -0.57571957],
       [ 0.75076744, -0.83286479],
       [-1.04368549, -1.46144199],
       [ 0.43409927, -0.23285928],
       [ 0.22298717, -0.74714972],
       [ 0.96187955,  0.56714807],
       [-0.19923705, -0.43286112],
       [-1.14924155, -1.03286663],
       [-1.36035365, -1.40429861],
       [-0.72701733, -0.54714788],
       [-1.36035365,  0.4528613 ],
       [ 0.01187506,  1.96716092],
       [ 0.32854322, -0.23285928],
       [-0.51590522,  0.51000468],
       [-0.30479311, -1.23286847],
       [-0.83257338,  0.33857454],
       [ 0.53965533, -0.09000083],
       [-0.41034916,  1.28144034],
       [-0.62146127, -0.29000266],
       [ 0.53965533, -0.40428943],
       [ 1.59521588,  2.33859291],
       [ 0.43409927,

In [19]:
reg = LogisticRegression()

In [21]:
regressor =reg.fit(x_train,y_train)

In [23]:
pre = reg.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
confusion_matrix(pre,y_test)

array([[47,  6],
       [ 8, 19]], dtype=int64)